backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1
  #name: git-gateway
  repo: korukugashi/plateau-debat-public-gatsby
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

site_url: https://debatpublic-bfc.netlify.app/
locale: 'fr'
#publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - label: "Agenda"
    name: "agenda"
    create: true
    folder: "src/pages/agenda/events"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "agenda"}
      - {label: "Date", name: "date", widget: "datetime", pickerUtc: false, dateFormat: "DD/MM/YYYY", timeFormat: "HH:mm"}
      - {label: "Titre", name: title, widget: string}
      - {label: "Lieu", name: location, widget: string}
      - {label: "Horaires / durée", name: duration, widget: string}
      - {label: "Informations complémentaires", name: "body", widget: "markdown", required: false}

  - label: "Partenaires"
    name: "partenaires"
    create: true
    slug: "{{label}}"
    folder: "src/pages/qui-sommes-nous/partenaires"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "partenaires"}
      - {label: "Libellé", name: label, widget: string}
      - {label: "Lien site", name: url, widget: string, required: false}
      - {name: image, label: Logo, widget: image, required: false}
  
  - name: team
    label: "Équipe"
    folder: "src/pages/qui-sommes-nous/equipe"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "equipe"}
      - { name: title, label: "Titre", default: "L'équipe du plateau débat public BFC" }
      - name: salaries
        label: Salariés
        widget: list
        fields:
          - { name: name, label: "Prénom et nom du salarié" }
          - { name: fonction, label: "Fonction" }
          - { name: photo, label: "Photo du salarié", widget: image}

  - label: "Catégories de documents"
    name: "categories"
    create: true
    slug: "{{label}}"
    folder: "src/pages/publications/categories"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "categories"}
      - {label: "Libellé", name: label, widget: string}

  - label: "Documents"
    name: "documents"
    create: true
    folder: "src/pages/publications/documents"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "documents"}
      - {label: "Date", name: "date", widget: "datetime", pickerUtc: false, dateFormat: "DD/MM/YYYY", timeFormat: "HH:mm"}
      - {label: "Titre", name: title, widget: string}
      - {label: "Description", name: "body", widget: "markdown"}
      - {label: "Fichier", name: file, widget: "file"}
      - {name: photo, label: "Photo de présentation", widget: image}
      - label: "Catégorie"
        name: category
        widget: "relation"
        collection: "categories"
        searchFields: ["label"]
        valueField: "label"
        displayFields: ["label"]
        multiple: false

  
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/qui-sommes-nous/index.md"
        label: "L'association"
        name: "association"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "association-page"}
          - {label: "Contenu de la page", name: "body", widget: "markdown"}
      - file: "src/pages/qui-sommes-nous/processus/index.md"
        label: "Processus"
        name: "processus"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "processus-page"}
          - {label: "Contenu de la page", name: "body", widget: "markdown"}

  - label: "Fichiers à partager"
    name: "files"
    create: true
    folder: "src/pages/files"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "files"}
      - {label: "Date", name: "date", widget: "datetime", pickerUtc: false, dateFormat: "DD/MM/YYYY", timeFormat: "HH:mm"}
      - {label: "Titre", name: title, widget: string}
      - {label: "Fichier", name: file, widget: "file"}
