backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1
  #name: git-gateway
  repo: korukugashi/plateau-debat-public-gatsby
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

site_url: https://debatpublic-bfc.netlify.app/
locale: 'fr'
#publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - label: "Évènements (agenda)"
    name: "events"
    slug: "{{year}}-{{slug}}"
    create: true
    folder: "src/pages/events"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "agenda"}
      - {label: "Date", name: "date", widget: "datetime", pickerUtc: false, dateFormat: "DD/MM/YYYY", timeFormat: "HH:mm"}
      - {label: "Titre", name: title, widget: string}
      - {name: photo, label: "Plaquette de présentation", widget: image}
      - {label: "Introduction (page accueil)", name: intro, widget: string}
      - {label: "Description complète", name: "body", widget: "markdown", required: false}

  - label: "Partenaires"
    name: "partenaires"
    create: true
    slug: "{{label}}"
    folder: "src/pages/qui-sommes-nous/partenaires"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "partenaires"}
      - {label: "Libellé", name: label, widget: string}
      - {label: "Lien site", name: url, widget: string, required: false}
      - {name: image, label: Logo, widget: image, required: false}
  
  - name: team
    label: "Équipe"
    folder: "src/pages/qui-sommes-nous/equipe"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "equipe"}
      - { name: title, label: "Titre", default: "L'équipe du plateau débat public BFC" }
      - name: salaries
        label: Salariés
        widget: list
        fields:
          - { name: name, label: "Prénom et nom du salarié" }
          - { name: fonction, label: "Fonction" }
          - { name: photo, label: "Photo du salarié", widget: image}

  - label: "CR Débats"
    name: "crdebats"
    slug: "{{year}}-{{slug}}"
    create: true
    folder: "src/pages/cr-debats"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "cr-debats"}
      - {label: "Titre", name: title, widget: string}
      - {label: "Lieu", name: location, widget: string, required: false}
      - {label: "Date", name: "date", widget: "date", pickerUtc: false, dateFormat: "DD/MM/YYYY"}
      - {label: "Description", name: description, widget: string, required: false}
      - { name: photo, label: "Plaquette de présentation", widget: image}
      - {label: "Lien CR", name: link, widget: string}
      - label: "Tags"
        name: "tags"
        widget: "relation"
        collection: "debattags"
        searchFields: ["label"]
        valueField: "label"
        displayFields: ["label"]
        multiple: true
      - {label: "Pour aller plus loin", name: "body", widget: "markdown", required: false}

  - label: "Lettre info"
    name: "lettreinfo"
    slug: "{{year}}-{{slug}}"
    create: true
    folder: "src/pages/publications/mots-et-debats"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "lettre-info"}
      - {label: "Titre", name: title, widget: string}
      - {label: "Date", name: "date", widget: "date", pickerUtc: false, dateFormat: "DD/MM/YYYY"}
      - {label: "Description", name: description, widget: string, required: false}
      - { name: photo, label: "Plaquette de présentation", widget: image}
      - {label: "Lien PDF", name: link, widget: string}

  - label: "Publications"
    name: "publications"
    slug: "{{year}}-{{slug}}"
    create: true
    folder: "src/pages/publications"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "publications"}
      - {label: "Titre", name: title, widget: string}
      - {label: "Date", name: "date", widget: "date", pickerUtc: false, dateFormat: "DD/MM/YYYY"}
      - {label: "Description", name: description, widget: string, required: false}
      - { name: photo, label: "Plaquette de présentation", widget: image}
      - {label: "Lien PDF", name: link, widget: string}
      - label: "Tags"
        name: "tags"
        widget: "relation"
        collection: "debattags"
        searchFields: ["label"]
        valueField: "label"
        displayFields: ["label"]
        multiple: true
      - {label: "Pour aller plus loin", name: "body", widget: "markdown", required: false}

  - label: "Tags"
    name: "debattags"
    create: true
    slug: "{{label}}"
    folder: "src/data/tags"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "debat-tags"}
      - {label: "Libellé", name: label, widget: string}
      - {name: image, label: Icône, widget: image}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/qui-sommes-nous/index.md"
        label: "L'association"
        name: "association"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "association-page"}
          - {label: "Contenu de la page", name: "body", widget: "markdown"}
      - file: "src/pages/qui-sommes-nous/processus/index.md"
        label: "Processus"
        name: "processus"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "processus-page"}
          - {label: "Contenu de la page", name: "body", widget: "markdown"}

  - label: "Fichiers à partager"
    name: "files"
    create: true
    folder: "src/pages/files"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "files"}
      - {label: "Date", name: "date", widget: "datetime", pickerUtc: false, dateFormat: "DD/MM/YYYY", timeFormat: "HH:mm"}
      - {label: "Titre", name: title, widget: string}
      - {label: "Fichier", name: file, widget: "file"}
